### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by UAEpro** [jbosboom/lynebot#1]
hello i tryed to fetch and compile then build with ant but when i click at jar files it's not working

**Comment by m3talstorm** [comment]
Make sure the game is running first

**Comment by UAEpro** [comment]
it is .. but nothing showing i just installed ant
then ant fetch; ant compile; ant build
and i went to build folder, launch game click on jar nothing happen :(
i get
"no main manifest attribute, in lynebot.jar"

**Comment by jbosboom** [comment]
The jar doesn't have the Main-Class or Class-Path manifest attributes set, so just double-clicking it won't work.  You'll need to run a command like `java -cp build\classes;lib\guava.jar com.jeffreybosboom.lyne.Effector` in the repository directory (or reference lynebot.jar if you built it).  (During development I always ran it from my IDE, which handles that automatically.)

As hinted in the readme, lynebot doesn't automate menus.  You need to be at the first puzzle of a set before running it.

**Comment by UAEpro** [comment]
Thanks .. it was my mistake .. very good work <3

**Comment by xenongee** [comment]
I compiled in ant, created a .bat to run and ... I get this error. What to do about it?
`T
Exception in thread "main" java.lang.IndexOutOfBoundsException: Index 1 out of bounds for length 1
        at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
        at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
        at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248)
        at java.base/java.util.Objects.checkIndex(Objects.java:373)
        at java.base/java.util.ArrayList.get(ArrayList.java:427)
        at com.jeffreybosboom.lyne.Puzzle.lambda$terminals$16(Puzzle.java:150)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.HashMap$ValueSpliterator.tryAdvance(HashMap.java:1787)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.lambda$initPartialTraversalState$0(StreamSpliterators.java:294)
        at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.fillBuffer(StreamSpliterators.java:206)
        at java.base/java.util.stream.StreamSpliterators$AbstractWrappingSpliterator.doAdvance(StreamSpliterators.java:161)
        at java.base/java.util.stream.StreamSpliterators$WrappingSpliterator.tryAdvance(StreamSpliterators.java:300)
        at java.base/java.util.Spliterators$1Adapter.hasNext(Spliterators.java:681)
        at com.jeffreybosboom.lyne.rules.TerminalTerminalRule.apply(TerminalTerminalRule.java:38)
        at com.jeffreybosboom.lyne.rules.TerminalTerminalRule.apply(TerminalTerminalRule.java:35)
        at java.base/java.util.function.Function.lambda$andThen$1(Function.java:88)
        at com.jeffreybosboom.lyne.Solver.solve(Solver.java:62)
        at com.jeffreybosboom.lyne.Effector.playPuzzle(Effector.java:76)
        at com.jeffreybosboom.lyne.Effector.main(Effector.java:151)`
![Screenshot](https://user-images.githubusercontent.com/43109023/90261315-741f0d80-de55-11ea-9fd8-30bd45c75580.png)
